title: Indoor-Outdoor Classifier
description: A simple web app to classify if an area is Indoor or Outdoor using FastAI and Gradio.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Navigation (only homepage)
header_pages:
  - index.html

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Custom variables
author: adilsiraju
